appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: B38lkRwNm3DRU46gRMpRBSw4NzH9oxzDI792YWViLo0f0mQwfpJNbK/ccl8K33YEy294FoBm2bXN5dS6MIv5xDCB/J12S2zGCeLOc708MFmx9soUt/XLroQmGLhh0TleDbR6NdFmqjBpEu8gnylmxW5HvWYGc4OGlyqmJmxIDTbwVy9K8gUsv0APx5emIJUl6fWst/hjcrsFTAnRc/gLrikBDgOZoskzTVBFaKxCLhH20yugePSDRr/0uBgx/d2Xcv37DPs126sd6i5mQxYQ4kMrPRBQb+T6sFYlu+HwQjZI3S1NjaLfZRf4saJNywawhkBD6EdI4+Po82JdTlsqqmwadCch3Vmatfm8vztki7Iz47CfJEoCipn8sIfSf9anr3n3A4JKSM5bOKQIvMkSthGuuaXVAb+0rPdKxErlqyN9KjvjDk5n2xyMrPGyaG8++5BpccgJM5lFvr/V0n7wid6HgulQR/2WvfuxwRB4MCYlgieefgBXJPBjDlDllJjGAqCBOo//ihhocBvqxt3lUA0yUGk/hJv96/6jmToLU9e7y7rV5IunJFV7+RIy2F4fL4nkCBOIyPT0cCvTLVElji8jbM52CeeXmh3nBCN7Zv257RhjkfWmPG16fDLJwqJUIMDjV7uiEpHcE37qOy89ITMRvNXjTVu1eWjO5+5Xiys=}
conda_forge_output_validation: true
