travis:
  secure:
    BINSTAR_TOKEN: v2HPxq7FsXI32faCVVSr/qAN/0WvYbWnxGJPzgNSTVD+WJGK2iwYN2uns1qCMAfQu4+ITSOH+4gCJPc7mdI46SSuFnv2RAlaccKQYqaMaIZMXksHryL5nR/e+LRwu8ycDK39xSEv/C8JZkDpUYb1GoudzDUy7ySgW4DnsgF6q9z/58uQ+ua8f+ETUh3e5/0PcA6TnEUmiQwM+QQTMVbrV1FwKeZ6TQd5WwYzMO7Ql9WvA/1XOr6DAvOJCwgH+1Fv3CH4na1kAiw/sLaIr7a9oUYsmuwHKbLBiGDOyCIbwhK2Exo+E1qKUl1dU6hhjOTaDHQ53BTXstlC1WlpLf5bLdfMwo7+Yp4mhhfkZ3ae7e2LWZOr+3r5vjJKlO/QxkhD+YfeTSeoe6dukYrSDQAxkUrNrLPgXw+1yJRvAx6bmMcYVUr8oF9OoT27BQjNbkagvLbS3WYbpcDkS7GiJFXiXC2Q3379Ds87zn4T9CHQ5BZ8pW6vzyKYmNFUtbFiPnP0q5MF2+JHxcHbWA2nyEeHogc0dRE6tbV7cYxxDIUNC0TrqmZWQ8aE4ELI/sQR6c+zs6R8h7HRGKC48IYuLGoZlELP9ayEUd/8yOT39eIgz932/VimJCAuDecQI/D7YAIciLKW2tCtXMqmBWq9dO3yTmGGBVdxQT6NSCqGnpqsV8E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
